---
title: "Project 1"
author: "Harshil"
date: "February 14, 2020"
output:
  pdf_document: default
  html_document: default
---

Importing library, data, cleaning:

```{r}

library(dplyr)
library(lubridate)
library(tidyr)
library(ggplot2)
library(wesanderson)
library(usmap)
library(treemap)
library(scales)

fmarket_raw <- read.csv("C:/Users/Harshil/Downloads/fmarket.csv", na.strings="", stringsAsFactors=FALSE)
us_regions <- read.csv("C:/Users/Harshil/Downloads/us_regions.csv", na.strings="", stringsAsFactors=FALSE)

fmarket <- merge(fmarket_raw, us_regions, by='State', all = T) #Adding regions

fmarket[is.na(fmarket$Region),'Region']<- 'South'

fmarket$updateTime <- parse_date_time(fmarket$updateTime, c('%b %d %Y %I:%M%p', '%m/%d/%Y %H:%M:%S %p', '%Y'))

```

Grant Data:

```{r}
grant <- read.csv("C:/Users/Harshil/Downloads/grant_awarded.csv", na.strings="", stringsAsFactors=FALSE)
applicantions <- read.csv("C:/Users/Harshil/Downloads/applicant.csv", na.strings="", stringsAsFactors=FALSE)
application_type <- read.csv("C:/Users/Harshil/Downloads/applicant_type.csv", na.strings="", stringsAsFactors=FALSE)
application_type$UnAwarded <- as.numeric(application_type$Number.of.Requests) - as.numeric( application_type$Number.of.Awards)

application_type <- gather(application_type, key = 'Accepted_Not.Accepted', value = 'Application', -c(1,2,4,5))

grant$Amount.Requested <- as.numeric(gsub('[$,]', '', grant$Amount.Requested))
grant$Amount.Awarded <- as.numeric(gsub('[$,]', '', grant$Amount.Awarded))
grant <- gather(grant, key = 'Type', value = 'Amount', - c('Fiscal.Year','X..Awarded'))


awardvsreq_plot <- ggplot(grant, aes(x= as.factor(Fiscal.Year), y= Amount, group = Type))+ geom_line(aes(colour = Type))+ geom_point()+ scale_y_continuous(labels = scales::dollar)+ labs(title = " Awarded vs Requested Grant Trend",x= 'Fiscal Year' , y= 'Amount')+ scale_color_discrete(name = 'Type', labels = c('Awarded','Requested'))

ggsave('awardvsreq_plot.png', awardvsreq_plot, dpi=300)

grantapplicant <- ggplot(top_n(application_type,8,Number.of.Requests), aes(x = reorder(Applicant.Type,Number.of.Requests), y= Application, fill= Accepted_Not.Accepted)) + geom_bar(type = 'stacked', stat='identity')+ scale_fill_discrete(name = 'Application status', labels = c('Awarded','Not Awarded'))+ labs(title = "Top 4 Applicants for the Grant And their Approvals in 2016", x= 'Applicant Type' , y= 'Applications')+theme(axis.text.x = element_text(angle = 30, hjust = 1), panel.grid.major.y = element_line(color = 'grey'))

ggsave('grantapplicant_plot.png', grantapplicant, dpi=450, scale= 3)

grantapplicant

awardvsreq_plot

```

Total Markets by state, aggregation of goods by state, perecentage of market selling those goods:
```{r}
totalByState <- fmarket %>%group_by(State) %>% summarise(total = n()) %>% arrange(desc(total))

mini_market <- fmarket[,c(1,2,30:58)]

pivotGoods <- mini_market %>% gather(key = 'Goods', value = 'YesNo', -FMID, -State)

agg_By_State_gather <- pivotGoods %>% filter( YesNo == 'Y') %>% group_by(State, Goods) %>% summarise(totalGoods = n()) 

agg_By_State <- agg_By_State_gather%>% spread( key = Goods, value = totalGoods)
agg_By_State <- merge(totalByState,agg_By_State, by= 'State')

percent_market <- agg_By_State_gather
percent_market <- merge(totalByState,percent_market, by= 'State')


percent_market$percent <- (percent_market$totalGoods/percent_market$total)*100
percent_spread <- spread(percent_market[,c(1,3,5)], key= Goods, value = percent)

#agg_By_State <- merge(totalreportByState,agg_By_State, by= 'State', all= T)
#agg_By_State$Organicperc <- agg_By_State$Organic/agg_By_State$total*100
#agg_By_State$Organicperc_reported <- agg_By_State$Organic/agg_By_State$totalReported*100
#sum(agg_By_State$Organic, na.rm= T)/ sum(agg_By_State$total, na.rm= T)
#sum(agg_By_State$Organic, na.rm= T)/ sum(agg_By_State$totalReported, na.rm= T)


```


```{r}

market_short <- percent_market %>% group_by(Goods) %>% top_n(-3) 

market_short$percent <- 100 - market_short$percent

goodshortage <- treemap(market_short,c('Goods' ,'State'), vSize = 'percent', type = 'index', title= "Goods and Shortage", overlap.labels = 0.5, align.labels = list(c("left", "top"), c("center", "bottom")))



```

Organic states

```{r}
totalreportByState <- fmarket %>% filter(Organic != '-') %>% group_by(State) %>% summarise(totalReported = n()) %>% arrange(desc(totalReported))

totalOrganic <- fmarket %>% filter(Organic == 'Y') %>% group_by(State) %>% summarise(totalOrganic = n()) %>% arrange(desc(totalOrganic)) %>% merge(totalreportByState, by= 'State')

totalOrganic$percent_organic <- (totalOrganic$totalOrganic/totalOrganic$totalReported)*100

totalOrganic$state <- totalOrganic$State

organicstate_plot <- plot_usmap(data = totalOrganic , values = "percent_organic") + 
  scale_fill_continuous(name = "Organic Percentage", label = scales::comma) + 
  theme(legend.position = "right")+ labs(title = "Reported Organic market % by States")

ggsave('organicstate.png',organicstate_plot ,dpi =320)

organicstate_plot

```


Different Type of Payments:

```{r}
WIC_market <- fmarket %>% filter(WIC == 'Y')
WICcash_market <- fmarket %>% filter(WICcash == 'Y')
SFMNP_market <- fmarket %>% filter(SFMNP == 'Y')
SNAP_market <- fmarket %>% filter(SNAP == 'Y')
credit_market <- fmarket %>% filter(Credit == 'Y')

payment_count <- fmarket[,c(24:28,61)] %>% gather(key = 'payment', value = 'YesNo', -Region) %>% filter( YesNo == 'Y') %>% group_by(Region, payment) %>% summarise(totalPaymentMarket= n()) 

us_payment <- fmarket[,c(24:28,61)] %>% gather(key = 'payment', value = 'YesNo', -Region) %>% filter( YesNo == 'Y') %>% group_by(payment) %>% summarise(totalMarket= n())

payment_count <- merge(payment_count, us_payment, by= 'payment')

payment_method_plot <- ggplot(payment_count, aes(x= reorder(payment,totalMarket), y = totalPaymentMarket, fill= Region, label = totalPaymentMarket))+ geom_bar(type = 'stacked', stat='identity')+ labs(y = 'Count of Markets accepting Payments', x = 'Types of Payment', fill= 'Regions')+ geom_text(size = 3, position = position_stack(vjust = 0.5))+ geom_hline(yintercept=8791, linetype="dashed")+
 annotate(geom="text",x=3, y=9200, label="Total Markets in US(approx 8800) accepting Cash")+ ylim(0,9200)

ggsave('payment_method_plot.png', payment_method_plot, dpi=320)

payment_method_plot
```

Market Not Participating in any program

```{r}

noProgramMarket <- fmarket %>% filter(Credit == 'Y' & WIC == 'N' & WICcash == 'N' & SFMNP == 'N'& SNAP == 'N') 

NP <- noProgramMarket[,c(2,30:58,61)] %>% gather(key = 'Goods', value = 'YesNo', -FMID, -Region) %>% filter( YesNo == 'Y') %>% group_by(FMID, Region) %>% summarise(totalGoods = n()) %>% group_by(Region) %>% summarise(AverageGoods = mean(totalGoods)) 

NP$type <- 'No Program'

WIC <- WIC_market[,c(2,30:58,61)] %>% gather(key = 'Goods', value = 'YesNo', -FMID, -Region) %>% filter( YesNo == 'Y') %>% group_by(FMID, Region) %>% summarise(totalGoods = n()) %>% group_by(Region) %>% summarise(AverageGoods = mean(totalGoods)) 

WIC$type <- 'WIC'

WICcash <- WICcash_market[,c(2,30:58,61)] %>% gather(key = 'Goods', value = 'YesNo', -FMID, -Region) %>% filter( YesNo == 'Y') %>% group_by(FMID, Region) %>% summarise(totalGoods = n()) %>% group_by(Region) %>% summarise(AverageGoods = mean(totalGoods)) 

WICcash$type <- 'WICcash'


SFMNP <- SFMNP_market[,c(2,30:58,61)] %>% gather(key = 'Goods', value = 'YesNo', -FMID, -Region) %>% filter( YesNo == 'Y') %>% group_by(FMID, Region) %>% summarise(totalGoods = n()) %>% group_by(Region) %>% summarise(AverageGoods = mean(totalGoods)) 

SFMNP$type <- 'SFMNP'


SNAP <- SNAP_market[,c(2,30:58,61)] %>% gather(key = 'Goods', value = 'YesNo', -FMID, -Region) %>% filter( YesNo == 'Y') %>% group_by(FMID, Region) %>% summarise(totalGoods = n()) %>% group_by(Region) %>% summarise(AverageGoods = mean(totalGoods)) 

SNAP$type <- 'SNAP'

pal <- wes_palette("Zissou1", 100, type = "continuous")

payment_variety<- ggplot(rbind(NP, WIC, WICcash, SFMNP, SNAP), aes(x = Region, y= type, fill = AverageGoods))+ geom_tile()+ labs(y = 'Types Payments', x = 'Region', fill= 'Variety of Goods', title = "Effect of programs on variety of food")

ggsave("payment_variet.png", payment_variety, dpi = 320)
payment_variety
```
